# Generated by Django 5.0.6 on 2024-12-30 06:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciepe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reciepe',
            name='receipe_image',
            field=models.ImageField(upload_to='receipe/'),
        ),
    ]
